# Generated by Django 4.0.5 on 2022-11-10 09:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 11, 10)),
        ),
    ]
