# Generated by Django 4.0.5 on 2022-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_jobs_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobs',
            name='qualifications',
            field=models.CharField(choices=[('PHD', 'PHD'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('High School', 'High School')], default='Degree', max_length=20),
        ),
    ]
