# Generated by Django 4.0.5 on 2022-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_jobs_logo_jobs_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='applied',
            field=models.IntegerField(default=0),
        ),
    ]
