# Generated by Django 4.0.5 on 2022-06-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_jobs_applied'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='applications',
        ),
        migrations.AddField(
            model_name='user_data',
            name='applications',
            field=models.ManyToManyField(to='application.jobs'),
        ),
    ]
