# Generated by Django 4.0.5 on 2022-06-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_user_data_applications_user_data_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='applications',
            field=models.ManyToManyField(blank=True, null=True, to='application.jobs'),
        ),
    ]
