# Generated by Django 4.0.5 on 2022-06-22 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_user_data_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='applications',
        ),
        migrations.AddField(
            model_name='user_data',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='UserJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ManyToManyField(to='application.jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.user_data')),
            ],
        ),
    ]
