# Generated by Django 4.0.5 on 2022-06-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_remove_user_data_applications_user_data_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='dog',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-Binary', 'Non-Binary')], default='Nairobi', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='highQ',
            field=models.CharField(blank=True, choices=[('PHD', 'PHD'), ('Degree', 'Degree'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('High School', 'High School')], default='Degree', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='institution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
