# Generated by Django 4.0.5 on 2022-06-23 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_user_data_city_alter_user_data_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='date_posted',
            field=models.DateField(default=datetime.date(2022, 6, 23)),
        ),
    ]
